### ISSUE TITLE
3rdParty/unzip/unzip.h:118:45: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'OF'

### ISSUE THREAD

**Issue by mmokrejs** [piratical/Madeline_2.0_PDE#36] opened 2016-08-01 17:07 UTC
Hi,
  I tried to compile from current HEAD but I receive:

```
...
Resolving user defined references...
Finding anchors and sections in the documentation...
Transferring function references...
Combining using relations...
Adding members to index pages...
In file included from /scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999/3rdParty/unzip/unzip.c:12:0:
/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999/3rdParty/unzip/unzip.h:118:45: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'OF'
 extern int ZEXPORT unzStringFileNameCompare OF ((const char* fileName1,
                                             ^
/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999/3rdParty/unzip/unzip.h:131:32: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'OF'
 extern unzFile ZEXPORT unzOpen OF((const char *path));
                                ^
/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999/3rdParty/unzip/unzip.h:142:29: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'OF'
 extern int ZEXPORT unzClose OF((unzFile file));
                             ^
/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999/3rdParty/unzip/unzip.h:149:37: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'OF'
 extern int ZEXPORT unzGetGlobalInfo OF((unzFile file,
                                     ^
/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999/3rdParty/unzip/unzip.h:157:40: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'OF'
 extern int ZEXPORT unzGetGlobalComment OF((unzFile file,
                                        ^
/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999/3rdParty/unzip/unzip.h:170:37: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'OF'
 extern int ZEXPORT unzGoToFirstFile OF((unzFile file));
                                     ^
/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999/3rdParty/unzip/unzip.h:176:36: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'OF'
 extern int ZEXPORT unzGoToNextFile OF((unzFile file));
                                    ^
/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999/3rdParty/unzip/unzip.h:183:34: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'OF'
 extern int ZEXPORT unzLocateFile OF((unzFile file, 
                                  ^
/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999/3rdParty/unzip/unzip.h:196:42: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'OF'
 extern int ZEXPORT unzGetCurrentFileInfo OF((unzFile file,
                                          ^
/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999/3rdParty/unzip/unzip.h:222:39: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'OF'
 extern int ZEXPORT unzOpenCurrentFile OF((unzFile file));
                                       ^
/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999/3rdParty/unzip/unzip.h:228:40: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'OF'
 extern int ZEXPORT unzCloseCurrentFile OF((unzFile file));
                                        ^
/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999/3rdParty/unzip/unzip.h:235:39: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'OF'
 extern int ZEXPORT unzReadCurrentFile OF((unzFile file, 
                                       ^
/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999/3rdParty/unzip/unzip.h:249:32: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'OF'
 extern z_off_t ZEXPORT unztell OF((unzFile file));
                                ^
/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999/3rdParty/unzip/unzip.h:254:27: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'OF'
 extern int ZEXPORT unzeof OF((unzFile file));
                           ^
/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999/3rdParty/unzip/unzip.h:259:42: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'OF'
 extern int ZEXPORT unzGetLocalExtrafield OF((unzFile file,
                                          ^
/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999/3rdParty/unzip/unzip.c: In function 'unzOpen':
/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999/3rdParty/unzip/unzip.c:431:2: warning: implicit declaration of function 'unzGoToFirstFile' [-Wimplicit-function-declaration]
  unzGoToFirstFile((unzFile)s); 
  ^
/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999/3rdParty/unzip/unzip.c: In function 'unzClose':
/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999/3rdParty/unzip/unzip.c:450:9: warning: implicit declaration of function 'unzCloseCurrentFile' [-Wimplicit-function-declaration]
         unzCloseCurrentFile(file);
         ^
/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999/3rdParty/unzip/unzip.c: At top level:
/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999/3rdParty/unzip/unzip.c:496:47: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'OF'
 local int unzlocal_GetCurrentFileInfoInternal OF((unzFile file,
                                               ^
make[2]: *** [3rdParty/unzip/CMakeFiles/unzip.dir/build.make:63: 3rdParty/unzip/CMakeFiles/unzip.dir/unzip.c.o] Error 1
```

Is there a way to disable compilation of the 3rd-party stuff? I have sys-libs/zlib with minizip support installed. ;-)
Better add it to the dependencies at http://madeline.med.umich.edu/madeline/building.php and drop it from your git tree. ;-)

**Comment by piratical** [comment] 2016-08-01 18:21
Can you tell me what specific platform you are compiling on?

**Comment by mmokrejs** [comment] 2016-08-01 19:13
Ah, sorry for being inexact. This is a Gentoo Linux, and I am stitching a package definition file so that it would be installed by its general package manager. I have gcc-5.4.0. I just need to tell cmake to skip this 3rdParty/unzip/ target.

**Comment by piratical** [comment] 2016-08-01 20:16
If you have time to make a nice patch for the cmake stuff that meets your
needs on Gentoo, I'll be happy to test whether it breaks anything on a few
other platforms and if all is OK we can add it to the repo.

(I'm currently really busy on other projects, so your help would be
appreciated :) )

Best -- Ed

**Comment by mmokrejs** [comment] 2016-08-02 21:58
Unfortunately it is out of my capability. I tried to disable the 3rd-party stuff calling but the unzip headers were called from elsewhere. I tried several gcc version, down to 4.3.6 but the error is same.

So, why is this unzip thing needed, why isn't my bzip2 and gzip enough? The initial cmake checks for dependencies seem to show everything is available. So, what is this unzip thing?
```

>>> Emerging (1 of 1) sci-biology/madeline-9999::science
>>> Unpacking source...
 * Fetching https://github.com/piratical/Madeline_2.0_PDE.git ...
git fetch https://github.com/piratical/Madeline_2.0_PDE.git +HEAD:refs/git-r3/HEAD
git symbolic-ref refs/git-r3/sci-biology/madeline/0/__main__ refs/git-r3/HEAD
 * Checking out https://github.com/piratical/Madeline_2.0_PDE.git to /scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999 ...
git checkout --quiet refs/git-r3/HEAD
GIT update -->
   repository:               https://github.com/piratical/Madeline_2.0_PDE.git
   at the commit:            2082ee74758e64d06d0900474815aeba493e65ea
>>> Source unpacked in /scratch/var/tmp/portage/sci-biology/madeline-9999/work
>>> Preparing source in /scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999 ...
>>> Source prepared.
>>> Configuring source in /scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999 ...
>>> Working in BUILD_DIR: "/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build"
cmake --no-warn-unused-cli -C /scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build/gentoo_common_config.cmake -G Unix Makefiles -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_INSTALL_DO_STRIP=OFF -DCMAKE_USER_MAKE_RULES_OVERRIDE=/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build/gentoo_rules.cmake -DCMAKE_TOOLCHAIN_FILE=/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build/gentoo_toolchain.cmake  /scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999
Not searching for unused variables given on the command line.
loading initial cache file /scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build/gentoo_common_config.cmake
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found BZip2: /usr/lib64/libbz2.so (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit in /usr/lib64/libbz2.so
-- Looking for BZ2_bzCompressInit in /usr/lib64/libbz2.so - found
-- WARNING: you are using the obsolete 'PKGCONFIG' macro, use FindPkgConfig
-- include dir is /usr/include
-- Found LibXml2: /usr/lib64/libxml2.so
-- Looking for dgettext
-- Looking for dgettext - found
-- Found Libintl: /usr/include
-- Looking for curl_easy_setopt
-- Looking for curl_easy_setopt - not found
-- Found Libcurl: /usr/include
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.8") 
-- Looking for include file malloc.h
-- Looking for include file malloc.h - found
-- Looking for include files sys/param.h, sys/mount.h
-- Looking for include files sys/param.h, sys/mount.h - found
-- === NOTA BENE: === Madeline will be installed in /usr
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.11") 
-- <<< Gentoo configuration >>>
Build type      Gentoo
Install path    /usr
Compiler flags:
C               -O2 
C++             -O2 
Linker flags:
Executable       -Wl,-O1 -Wl,--as-needed
Module           -Wl,-O1 -Wl,--as-needed
Shared           -Wl,-O1 -Wl,--as-needed

-- Configuring done
-- Generating done
-- Build files have been written to: /scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build
>>> Source configured.
>>> Compiling source in /scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999 ...
>>> Working in BUILD_DIR: "/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build"
make -j2 VERBOSE=1 
/usr/bin/cmake -H/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999 -B/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build/CMakeFiles /scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build'
make -f CMakeFiles/api-docs.dir/build.make CMakeFiles/api-docs.dir/depend
make -f 3rdParty/unzip/CMakeFiles/unzip.dir/build.make 3rdParty/unzip/CMakeFiles/unzip.dir/depend
make[2]: Entering directory '/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build'
cd /scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999 /scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999 /scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build /scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build /scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build/CMakeFiles/api-docs.dir/DependInfo.cmake --color=
make[2]: Entering directory '/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build'
cd /scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999 /scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999/3rdParty/unzip /scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build /scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build/3rdParty/unzip /scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build/3rdParty/unzip/CMakeFiles/unzip.dir/DependInfo.cmake --color=
Dependee "/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build/CMakeFiles/api-docs.dir/DependInfo.cmake" is newer than depender "/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build/CMakeFiles/api-docs.dir/depend.internal".
Dependee "/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build/CMakeFiles/api-docs.dir/depend.internal".
Scanning dependencies of target api-docs
Dependee "/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build/3rdParty/unzip/CMakeFiles/unzip.dir/DependInfo.cmake" is newer than depender "/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build/3rdParty/unzip/CMakeFiles/unzip.dir/depend.internal".
Dependee "/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build/3rdParty/unzip/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build/3rdParty/unzip/CMakeFiles/unzip.dir/depend.internal".
Scanning dependencies of target unzip
make[2]: Leaving directory '/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build'
make -f CMakeFiles/api-docs.dir/build.make CMakeFiles/api-docs.dir/build
make[2]: Entering directory '/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build'
/usr/bin/doxygen /scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build/doxygen/Doxyfile
make[2]: Leaving directory '/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build'
make -f 3rdParty/unzip/CMakeFiles/unzip.dir/build.make 3rdParty/unzip/CMakeFiles/unzip.dir/build
warning: Tag `USE_WINDOWS_ENCODING' at line 54 of file `/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build/doxygen/Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag `DETAILS_AT_TOP' at line 202 of file `/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build/doxygen/Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag `HTML_ALIGN_MEMBERS' at line 532 of file `/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build/doxygen/Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag `XML_SCHEMA' at line 766 of file `/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build/doxygen/Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag `XML_DTD' at line 772 of file `/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build/doxygen/Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag `MAX_DOT_GRAPH_WIDTH' at line 1026 of file `/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build/doxygen/Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag `MAX_DOT_GRAPH_HEIGHT' at line 1034 of file `/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build/doxygen/Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag `CGI_NAME' at line 1072 of file `/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build/doxygen/Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag `CGI_URL' at line 1078 of file `/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build/doxygen/Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag `DOC_URL' at line 1084 of file `/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build/doxygen/Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag `DOC_ABSPATH' at line 1090 of file `/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build/doxygen/Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag `BIN_ABSPATH' at line 1095 of file `/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build/doxygen/Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag `EXT_DOC_PATHS' at line 1101 of file `/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build/doxygen/Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
make[2]: Entering directory '/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build'
[  1%] Building C object 3rdParty/unzip/CMakeFiles/unzip.dir/unzip.c.o
cd /scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build/3rdParty/unzip && /usr/bin/x86_64-pc-linux-gnu-gcc     -DNDEBUG -O2    -o CMakeFiles/unzip.dir/unzip.c.o -c /scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999/3rdParty/unzip/unzip.c
Searching for include files...
Searching for example files...
Searching for images...
Searching for dot files...
Searching for msc files...
Searching for dia files...
Searching for files to exclude
Searching INPUT for files to process...
Searching for files in directory /scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build/src
Searching for files in directory /scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build/src/CMakeFiles
Searching for files in directory /scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build/src/CMakeFiles/madeline2.dir
Reading and parsing tag files
Parsing files
Building group list...
Building directory list...
Building namespace list...
Building file list...
Building class list...
Associating documentation with classes...
Computing nesting relations for classes...
Building example list...
Searching for enumerations...
Searching for documented typedefs...
Searching for members imported via using declarations...
Searching for included using directives...
Searching for documented variables...
Building interface member list...
Building member list...
Searching for friends...
Searching for documented defines...
Computing class inheritance relations...
Computing class usage relations...
Flushing cached template relations that have become invalid...
Creating members for template instances...
Computing class relations...
Add enum values to enums...
Searching for member function documentation...
Building page list...
Search for main page...
Computing page relations...
Determining the scope of groups...
Sorting lists...
Freeing entry tree
Determining which enums are documented
Computing member relations...
Building full member lists recursively...
Adding members to member groups.
Computing member references...
Inheriting documentation...
Generating disk names...
Adding source references...
Adding xrefitems...
Sorting member lists...
Computing dependencies between directories...
Generating citations page...
Counting data structures...
Resolving user defined references...
Finding anchors and sections in the documentation...
Transferring function references...
Combining using relations...
Adding members to index pages...
Generating style sheet...
Generating search indices...
Generating example documentation...
Generating file sources...
Generating file documentation...
Generating page documentation...
Generating group documentation...
Generating class documentation...
Generating namespace index...
Generating graph info page...
Generating directory documentation...
Generating index page...
Generating page index...
Generating module index...
Generating namespace index...
Generating namespace member index...
Generating annotated compound index...
Generating alphabetical compound index...
Generating hierarchical class index...
Generating member index...
Generating file index...
Generating file member index...
Generating example index...
finalizing index lists...
writing tag file...
lookup cache used 0/65536 hits=0 misses=0
finished...
make[2]: Leaving directory '/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999_build'
In file included from /scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999/3rdParty/unzip/unzip.c:12:0:
/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999/3rdParty/unzip/unzip.h:118:45: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'OF'
 extern int ZEXPORT unzStringFileNameCompare OF ((const char* fileName1,
                                             ^
/scratch/var/tmp/portage/sci-biology/madeline-9999/work/madeline-9999/3rdParty/unzip/unzip.h:131:32: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'OF'
 extern unzFile ZEXPORT unzOpen OF((const char *path));

...
```

**Comment by piratical** [comment] 2016-08-03 20:44
OK, I can take a look at this. I'll have to build a Linux virtual machine as I currently am doing most of my dev work on Apple OS X, so it might be a while but if I can reproduce the error, then I'll fix it. It is really a CMAKE issue, but CMAKE is not really my forté ...

Best -- Ed

**Comment by piratical** [comment] 2023-02-10 02:45
I'm going to close this issue as it is too old. I just downloaded and built Madeline2 on Ubuntu 22.04 with no issues and I am not able to reproduce the issue at all.

**Closed by piratical** 2023-02-10 02:45 UTC
